language: cpp
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages:
           - gcc-4.8
           - g++-4.8
           - valgrind
           - cmake
           - libboost-all-dev
install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - make
