defaults: &defaults
  working_directory: /tmp/build
  docker:
    - image: uubk/cinit-build:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: checkout submodules
          command: git submodule update --init
      - run:
          name: build
          command: mkdir build && cd build && cmake .. && make -j4
      - persist_to_workspace:
          root: build
          paths:
            - cinit
            - zombie
  smoke-test:
    machine: true
    working_directory: /tmp/build
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build/build
      - run:
          name: Install runtime dependencies
          command: sudo apt update && sudo apt install -y libyaml-cpp0.5v5 libboost-program-options1.62.0 libcap2
      - run:
          name: Run smoke test
          command: sudo .circleci/smoke-test.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - smoke-test:
          requires:
            - build
