defaults: &defaults
  working_directory: /tmp/build
  docker:
    - image: uubk/scinit-build:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: checkout submodules
          command: git submodule update --init
      - run:
          name: build
          command: mkdir build && cd build && cmake .. && make -j4
      - run:
          name: extract Debian 9 libs for ubuntu 14.04 testrunner
          command: |
            cp /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.62.0 /tmp/build/build && \
            cp /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.62.0 /tmp/build/build && \
            cp /usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0 /tmp/build/build && \
            cp /lib/x86_64-linux-gnu/libcap.so.2.25 /tmp/build/build && \
            cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22 /tmp/build/build && \
            cp /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.5.2 /tmp/build/build
      - persist_to_workspace:
          root: build
          paths:
            - scinit
            - zombie
            - libcap.so.2.25
            - libboost_program_options.so.1.62.0
            - libboost_system.so.1.62.0
            - libboost_filesystem.so.1.62.0
            - libstdc++.so.6.0.22
            - libyaml-cpp.so.0.5.2
  smoke-test:
    machine: true
    working_directory: /tmp/build
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build/build
      - run:
          name: Symlink libs
          command: |
            cd build && ln -s libcap.so.2.25 libcap.so.2 && \
            ln -s libstdc++.so.6.0.22 libstdc++.so.6 && \
            ln -s libyaml-cpp.so.0.5.2 libyaml-cpp.so.0.5
      - run:
          name: Run smoke test
          command: sudo .circleci/smoke-test.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - smoke-test:
          requires:
            - build
