version: 2
jobs:
  build:
    docker:
      - image: uubk/cinit-build:latest
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init
      - run:
          name: Build
          command: mkdir build && cd build && cmake .. && make
